blog/urls.py
from django.conf.urls import url

from . import views
from .views import RSSFeed

app_name = 'blog'

urlpatterns = [
    url(r'^home/$',views.home,name='home'),
    url(r'^time/$',views.current_datetime,name='current_datetime'),
    url(r'^test_time/$',views.test_time,name='test_time'),
    url(r'^detail/(?P<id>\d+)/$',views.detail,name='detail'),
    url(r'^archives/$',views.archives,name='archives'),
    url(r'^about_me/$',views.about_me,name='about_me'),
    url(r'^search_tag/(?P<tag>\w+)/$',views.search_tag,name='search_tag'),
    url(r'^search/$',views.blog_search,name='search'),
    url(r'^feed/',RSSFeed(),name="RSS"),
]

suynblog/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/',include('blog.urls')),
]

blog/models.py
from __future__ import unicode_literals
from django.core.urlresolvers import reverse
from django.db import models

# Create your models here.

class Article(models.Model):
	title = models.CharField(max_length=100)  #blog title
	category = models.CharField(max_length=50,blank=True)  #blog tag
	date_time = models.DateTimeField(auto_now_add=True)  #blog date
	content = models.TextField(blank=True,null=True)  #blog content

	def get_absolute_url(self):
		path = reverse('blog:detail',kwargs={'id':self.id})
		return "http:127.0.0.1:8001%s" % path

	def __unicode__(self):
		return self.title

	class Meta:
		ordering = ['-date_time']

blog/views.py
from django.shortcuts import render
from django.http import HttpResponse,Http404
from django.contrib.syndication.views import Feed
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger

import datetime

from .models import Article

# Create your views here.

def home(request):
	'''#return HttpResponse("hello world,django.")
	post_list = Article.objects.all()
	return render(request,'home.html',{'post_list' : post_list})'''
	posts = Article.objects.all()
	paginator = Paginator(posts,2)  #each page show 2 passages
	page = request.GET.get('page')
	try:
		post_list = paginator.page(page)
	except PageNotAnInteger:
		post_list = paginator.page(1)
	except EmptyPage:
		post_list = paginator.paginator(paginator.num_pages)
	return render(request,'home.html',{'post_list':post_list})

def current_datetime(request):
	now = datetime.datetime.now()
	html = "<html><body>It is now %s.</body></html>" % now
	return HttpResponse(html)
def test_time(request):
	return render(request,'test.html',{'current_time':datetime.datetime.now()})

def detail1(request, my_args):
	#return HttpResponse("You're looking at my_args %s." % my_args)
	post = Article.objects.all()[int(my_args)]
	str = ("title = %s, category = %s, date_time = %s, content = %s" % (post.title, post.category, post.date_time, post.content))
	return HttpResponse(str)

def detail(request,id):
	try:
		post = Article.objects.get(id=int(id))  #id:unicode -> int
	except Article.DoesNotExist:
		raise Http404
	return render(request,'post.html',{'post':post})

def archives(request):## simple list
	try:
		post_list = Article.objects.all()
	except Article.DoesNotExist:
		raise Http404
	return render(request,'archives.html',{'post_list' : post_list,'error':False})

def about_me(request):
	return render(request,'aboutme.html')

def search_tag(request,tag):
	try:
		post_list = Article.objects.filter(category__icontains = tag)
	except Article.DoesNotExist:
		raise Http404
	return render(request, 'tag.html', {'post_list' : post_list})

def blog_search(request):
	if 's' in request.GET:
		s = request.GET['s']
		if not s:
			return render(request,'home.html')
		else:
			post_list = Article.objects.filter(title__icontains = s)
			if len(post_list) == 0:
				return render(request,'archives.html', {'post_list' : post_list,'error' : True})
			else:
				return render(request,'archives.html', {'post_list' : post_list,'error' : False})

class RSSFeed(Feed):
	title = "RSS feed - article"
	link = "feeds/posts"
	description = "RSS feed - blog posts"

	def items(self):
		return Article.objects.order_by('-date_time')

	def item_title(self,item):
		return item.title
	def item_pubdate(self,item):
		return item.date_time
	def item_description(self,item):
		return item.content

templates/aboutme.html
{% extends "base.html" %}


{% block content %}
<div class="posts">
        <p> About Me ......my first django web. </p>
</div><!-- /.blog-post -->
{% endblock %}

templates/archives.html
{% extends "base.html" %}

{% block content %}
<div class="posts">
    {% if error %}
        <h2 class="post-title">no related passage title</h2>
    {% else %}
    {% for post in post_list %}
        <section class="post">
            <header class="post-header">
                <h2 class="post-title"><a href="{% url 'blog:detail' id=post.id %}">{{ post.title }}</a></h2>
                    <p class="post-meta">
                        Time:  <a class="post-author" href="#">{{ post.date_time |date:'Y /m /d'}}</a>
                        <a class="post-category post-category-js" href="{% url 'blog:search_tag' tag=post.category %}">
                        {{ post.category }}
                        </a>
                    </p>
            </header>
        </section>
    {% endfor %}
    {% endif %}
</div><!-- /.blog-post -->
{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="A layout example that shows off a blog page with a list of posts.">

    <title>suyn Blog</title>
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.5.0/pure-min.css">
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.5.0/grids-responsive-min.css">
    <link rel="stylesheet" href="http://picturebag.qiniudn.com/blog.css">
    <link rel="stylesheet" href="http://picturebag.qiniudn.com/monokai.css">
</head>
<body>
<div id="layout" class="pure-g">
    <div class="sidebar pure-u-1 pure-u-md-1-4">
        <div class="header">
            <h1 class="brand-title">suyn Blog</h1>
            <h2 class="brand-tagline">Bioinformatics</h2>
            <nav class="nav">
                <ul class="nav-list">
                    <li class="nav-item">
                        <a class="button-success pure-button" href="/">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="button-success pure-button" href="/">Archive</a>
                    </li>
                    <li class="nav-item">
                        <a class="pure-button" href="https://github.com/suyanan" target="_blank">Github</a>
                    </li>
                    <li class="nav-item">
                        <a class="pure-button" href="http://weibo.com/freeknighter" target="_blank">Weibo</a>
                    </li>
                    <li class="nav-item">
                        <a class="button-success pure-button" href="/">Subject</a>
                    </li>
                    <li class="nav-item">
                        <a class="button-success pure-button" href="/">About Me</a>
                    </li>

                    <li>
                    <form class="pure-form" action="{% url 'blog:search' %}" method="get">
                    <input class="pure-input-3-3" type="text" name="s" placeholder="searcher">
                    </form>
                    </li>

                    <li class="nav-item">
                        <a class="button-success pure-button" href="{% url 'blog:RSS' %}">RSS</a>  
                    </li>

                </ul>
            </nav>
        </div>
    </div>

    <div class="content pure-u-1 pure-u-md-3-4">
        <div>
            {% block content %}
            {% endblock %}
            <div class="footer">
                <div class="pure-menu pure-menu-horizontal pure-menu-open">
                    <ul>
                        <li><a href="http://andrewliu.tk/about/">About Me</a></li>
                        <li><a href="http://github.com/yahoo/pure/">GitHub</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

</body>
</html>

templates/duoshuo.html
<!-- duoshuo conmment box start -->
<div class="ds-thread" data-thread-key="{{ post.id }}" data-title="{{ post.title }}" data-url="{{ post.get_absolute_url }}">
</div>
<!-- end -->
<!-- duoshuo JS code start-->
<script type="text/javascript">
var duoshuoQuery = {short_name:"FreeKnighter"};
(function() {
    var ds = document.createElement('script');
    ds.type = 'text/javascript';ds.async = true;
    ds.src = (document.location.protocol == 'https:' ? 'https:' : 'http:') + '//static.duoshuo.com/embed.js';
    ds.charset = 'UTF-8';
    (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(ds);
})();
</script>
<!-- end -->

templates/home.html
{% extends "base.html" %}
{% load custom_markdown %}

{% block content %}
<div class="posts">
    {% for post in post_list %}
        <section class="post">
            <header class="post-header">
                <h2 class="post-title">{{ post.title }}</h2>
                    <p class="post-meta">
                        Time:  <a class="post-author" href="#">{{ post.date_time |date:'Y /m /d'}}</a>
                        <a class="post-category post-category-js" href="{% url 'blog:search_tag' tag=post.category %}">
                        {{ post.category |title }}
                        </a>
                    </p>
            </header>

                <div class="post-description">
                    <p>
                        {{ post.content |custom_markdown | truncatewords:35 }}
                    </p>
                </div>
                <a class="pure-button" href="{% url 'blog:detail' id=post.id %}">Read More >>> </a>
        </section>
    {% endfor %}
    {% if post_list.object_list and post_list.paginator.num_pages > 1 %}
        <div>
            <ul class="pager">
                {% if post_list.has_previous %}
                <li><a href="?page={{ post_list.previous_page_number }}">上一页</a></li>
                {% endif %}
                {% if post_list.has_next %}
                <li><a href="?page={{ post_list.next_page_number }}">下一页</a></li>
                {% endif %}
            </ul>
        </div>
    {% endif%}
</div><!-- /.blog-post -->
{% endblock %}

templates/post.html
{% extends "base.html" %}
{% load custom_markdown %}

{% block content %}
<div class="posts">
        <section class="post">
            <header class="post-header">
                <h2 class="post-title">{{ post.title }}</h2>
                    <p class="post-meta">
                        Time:  <a class="post-author" href="#">{{ post.date_time|date:'Y /m /d'}}</a>
                        <a class="post-category post-category-js" href="{% url 'blog:search_tag' tag=post.category %}">
                        {{ post.category }}
                        </a>
                    </p>
            </header>

                <div class="post-description">
                    <p>
                        {{ post.content |custom_markdown }}
                    </p>
                </div>
        </section>
        {% include "duoshuo.html" %}
</div><!-- /.blog-post -->
{% endblock %}

templates/tag.html
{% extends "base.html" %}

{% block content %}
<div class="posts">
    {% for post in post_list %}
        <section class="post">
            <header class="post-header">
                <h2 class="post-title"><a href="{% url 'blog:detail' id=post.id %}">{{ post.title }}</a></h2>
                    <p class="post-meta">
                        Time:  <a class="post-author" href="#">{{ post.date_time |date:'Y /m /d'}}</a>
                        <a class="post-category post-category-js" href="#%}">
                        {{ post.category | title }}
                        </a>
                    </p>
            </header>
        </section>
    {% endfor %}
</div><!-- /.blog-post -->
{% endblock %}

templates/test.html
<!DOCTYPE html>
<html>
<head>
	<title>just test template</title>
	<style>
		body{
			background-color: red;
		}
		em{
			color: LightSeaGreen;
		}
	</style>
</head>
<body>
    <h1>hello world</h1>
    <strong>{{ current_time }}</strong>
    <br>
    <em>hello</em>

</body>
</html>